name: "Sync with upstream"
on:
  push:
    branches: master
  schedule:
    # 1:05 past midnight UTC
    - cron: "5 1 * * *"


jobs:
    sync:
      name: "Sync"
      runs-on: "ubuntu-latest"
      permissions:
        issues: write
      env:
        DEFAULT_BRANCH: "master"
  
      steps:
        - name: "Checkout source code"
          uses: "actions/checkout@v3"
          with:
            # Subsequent actions are not triggered unless using PAT
            token: ${{ secrets.GITHUB_TOKEN }}
            fetch-depth: 0
            submodules: true
  
        - name: "Setup toolchain"
          uses: "actions-rs/toolchain@v1"
          with:
            toolchain: "stable"
            profile: "minimal"
            override: true
  
        - name: "Config Git"
          run: |
            git config user.name "Johnaverse"
            git config user.email "johnathan.leung@johnaverse.cloud	"
  
        - name: repo-sync
          uses: repo-sync/github-sync@v2
          with:
            source_repo: "https://github.com/telekom-security/tpotce.git"
            source_branch: "*"
            destination_branch: "*"
            github_token: ${{ secrets.GITHUB_TOKEN }}
            sync_tags: "true"